[env]
TERM = "xterm-256color"

[terminal]
shell = { program = "/opt/homebrew/bin/bash", args = ["--login", "-i"] }

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "6", mods = "Control", chars = "\u001e" },
]
