[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[terminal]
shell = {program = "C:\\Program Files\\PowerShell\\7\\pwsh.exe", args = ["-i"]}

[window]
padding.x = 10
padding.y = 10
decorations = "Full"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true
