[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "None"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{key="N",mods = "Control|Shift", action="CreateNewWindow"}]
